import json

with open('backend/all_users_dump.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

supabase_users = {u['id']: u for u in data['supabase']}
sqlite_users = {u['id']: u for u in data['sqlite']}
all_ids = sorted(set(supabase_users.keys()) | set(sqlite_users.keys()))

classified = []

for uid in all_ids:
    u = supabase_users.get(uid) or sqlite_users.get(uid)
    username = (u.get('username') or '').strip()
    email = (u.get('email') or '').strip()
    full_name = (u.get('full_name') or '').strip()
    role = (u.get('role') or '').strip()
    status = (u.get('status') or '').strip()
    ministry = u.get('ministry')
    project_id = u.get('project_id')
    clerk_user_id = u.get('clerk_user_id')

    # Determine classification
    is_admin = (role == 'ADMIN' or username in ('admin', 'LOG_bit'))
    
    # Check if test / demo
    is_test = False
    reasons = []

    # Patterns indicating automated test / demo data
    lower_uname = username.lower()
    lower_email = email.lower()
    lower_name = full_name.lower()

    if lower_uname in ('admin', 'LOG_bit') and is_admin:
        is_test = False
    elif lower_uname == 'fake_admin_reg':
        is_test = True
        reasons.append("Created by security test suite (fake_admin_reg)")
    elif lower_uname.startswith('archived_user_') or '@infranetra.internal' in lower_email:
        is_test = True
        reasons.append("Archived test placeholder record")
    elif lower_uname.startswith('clerk_min_') or lower_uname.startswith('clerk_pm_'):
        is_test = True
        reasons.append("Generated by clerk_integration_tests.py suite")
    elif lower_uname.startswith('sec_test_') or 'sec_test' in lower_email or 'officer_a@ministrya' in lower_email:
        is_test = True
        reasons.append("Generated by security_test_suite.py")
    elif lower_uname.startswith('pm_scope_test_') or 'pm1@infra.gov.in' in lower_email or 'pm2@fake.gov.in' in lower_email:
        is_test = True
        reasons.append("Generated by pm_ministry_scoping_tests.py")
    elif lower_uname.startswith('pub_test_') or 'pub_min@gov.in' in lower_email or 'pub_pm@gov.in' in lower_email:
        is_test = True
        reasons.append("Generated by public_mode_security_tests.py")
    elif lower_uname.startswith('resp_test_') or 'resp_test_min@nic.in' in lower_email or 'resp_test_pm@railways' in lower_email:
        is_test = True
        reasons.append("Generated by responsive_registration_tests.py")
    elif lower_uname.startswith('test_ux_') or 'ux_min@morth.nic.in' in lower_email or 'ux_pm@railways.gov.in' in lower_email:
        is_test = True
        reasons.append("Generated by registration_password_ux_tests.py")
    elif lower_uname.startswith('pd_min_') or lower_uname.startswith('pd_pm_') or lower_uname.startswith('pd_rej_'):
        is_test = True
        reasons.append("Generated by post_deploy_verification.py")
    elif lower_uname.startswith('e2e_min_') or lower_uname.startswith('e2e_pend_') or '@test.gov.in' in lower_email:
        is_test = True
        reasons.append("Generated by E2E automation tests")
    elif lower_uname.startswith('test_') or 'test' in lower_uname:
        is_test = True
        reasons.append("Test username prefix")
    elif 'test' in lower_name and not is_admin:
        is_test = True
        reasons.append("Synthetic test name")

    category = "REAL_ADMIN" if is_admin else ("TEST_DEMO_CANDIDATE" if is_test else "GENUINE_USER")

    classified.append({
        "id": uid,
        "username": username,
        "email": email,
        "full_name": full_name,
        "role": role,
        "status": status,
        "ministry": ministry,
        "project_id": project_id,
        "clerk_user_id": clerk_user_id,
        "category": category,
        "reasons": reasons,
        "in_supabase": uid in supabase_users,
        "in_sqlite": uid in sqlite_users,
    })

with open('backend/classified_candidates.json', 'w', encoding='utf-8') as f:
    json.dump(classified, f, indent=2)

print(f"Total evaluated users: {len(classified)}")
admins = [c for c in classified if c['category'] == 'REAL_ADMIN']
genuine = [c for c in classified if c['category'] == 'GENUINE_USER']
test_candidates = [c for c in classified if c['category'] == 'TEST_DEMO_CANDIDATE']
pending_test_candidates = [c for c in test_candidates if c['status'] == 'PENDING']

print(f"Real Admins: {len(admins)}")
for a in admins:
    print(f"  ADMIN -> ID={a['id']} | user={a['username']} | email={a['email']} | name={a['full_name']}")

print(f"\nGenuine Non-Admin Users: {len(genuine)}")
for g in genuine:
    print(f"  GENUINE -> ID={g['id']} | role={g['role']} | status={g['status']} | user={g['username']} | email={g['email']} | name={g['full_name']} | min={g['ministry']} | proj={g['project_id']}")

print(f"\nTest/Demo Candidates: {len(test_candidates)} (of which {len(pending_test_candidates)} are currently PENDING in Admin Approval Queue)")
