-- ==============================================================================
-- INFRASTRUCTURE PROJECTS SCHEMA FOR SUPABASE / POSTGRESQL
-- MoSPI PAIMANA Flash Report Ingestion & Historical Monitoring
-- ==============================================================================

-- Create the infrastructure_projects table
CREATE TABLE IF NOT EXISTS infrastructure_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id text NOT NULL,
    project_name text,
    agency text,
    ministry text,
    sector text,
    state text,
    start_date text,
    original_completion_date text,
    revised_completion_date text,
    actual_completion_date text,
    original_cost numeric,
    revised_cost numeric,
    expenditure numeric,
    physical_progress numeric,
    report_month date NOT NULL,
    source_section text,
    source_pages text,
    created_at timestamptz DEFAULT now(),

    -- Composite unique constraint: preserves historical monthly snapshots
    -- e.g. (705728, '2026-04-01') vs (705728, '2026-05-01') are two valid snapshots
    CONSTRAINT unique_project_report_month UNIQUE (project_id, report_month)
);

-- Performance and query indexes
CREATE INDEX IF NOT EXISTS idx_infra_projects_report_month ON infrastructure_projects(report_month);
CREATE INDEX IF NOT EXISTS idx_infra_projects_project_id ON infrastructure_projects(project_id);
CREATE INDEX IF NOT EXISTS idx_infra_projects_sector ON infrastructure_projects(sector);
CREATE INDEX IF NOT EXISTS idx_infra_projects_ministry ON infrastructure_projects(ministry);
CREATE INDEX IF NOT EXISTS idx_infra_projects_state ON infrastructure_projects(state);

-- Enable Row Level Security (RLS)
ALTER TABLE infrastructure_projects ENABLE ROW LEVEL SECURITY;

-- Allow read-only public access to verified project snapshots
CREATE POLICY "Allow public read access"
ON infrastructure_projects
FOR SELECT
TO anon, authenticated
USING (true);

-- Allow service_role full read and write access for FastAPI backend ingestion
CREATE POLICY "Allow service role full access"
ON infrastructure_projects
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
