-- ==============================================================================
-- INFRANETRA OPERATIONAL & AUTH POSTGRESQL SCHEMA FOR SUPABASE
-- Authoritative Persistence for Users, Scoping, PM Approvals, Daily Updates & Audit
-- ==============================================================================

-- 1. Unified User Identity and Credentials Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    designation TEXT,
    role TEXT NOT NULL CHECK(role IN ('ADMIN', 'MINISTRY', 'PROJECT_MANAGER', 'PUBLIC')),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')),
    clerk_user_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users(LOWER(username));
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_clerk_id ON users(clerk_user_id) WHERE clerk_user_id IS NOT NULL;

-- 2. Single Authoritative Ministry Assignment Table
CREATE TABLE IF NOT EXISTS user_ministry_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ministry TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING', 'ACTIVE', 'REVOKED')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_ministry UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_uma_user_id ON user_ministry_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_uma_ministry ON user_ministry_assignments(ministry);

-- 3. Single Authoritative Project Manager Assignment Table
CREATE TABLE IF NOT EXISTS project_manager_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING', 'ACTIVE', 'REVOKED')),
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_pm UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_pma_user_id ON project_manager_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_pma_project_id ON project_manager_assignments(project_id);

-- MANDATORY DATABASE RULE: ONE PROJECT ID = MAXIMUM ONE CURRENT (ACTIVE OR PENDING) PROJECT MANAGER
DROP INDEX IF EXISTS idx_unique_active_pm;
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_active_or_pending_pm ON project_manager_assignments(project_id) WHERE status IN ('ACTIVE', 'PENDING');


-- 4. Controlled Daily Project Updates Table
CREATE TABLE IF NOT EXISTS daily_project_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    manager_user_id BIGINT NOT NULL REFERENCES users(id),
    update_date DATE NOT NULL,
    today_physical_progress NUMERIC DEFAULT 0.0,
    cumulative_physical_progress NUMERIC NOT NULL,
    today_expenditure NUMERIC DEFAULT 0.0,
    cumulative_expenditure NUMERIC NOT NULL,
    milestone_status TEXT,
    current_milestone TEXT,
    target_completion_date TEXT,
    issues_risks TEXT,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dpu_project_id ON daily_project_updates(project_id);
CREATE INDEX IF NOT EXISTS idx_dpu_manager ON daily_project_updates(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_dpu_update_date ON daily_project_updates(update_date);

-- 5. Authoritative Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    actor_username TEXT,
    actor_role TEXT,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    details TEXT,
    ip_address TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    result TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_actor_username ON audit_logs(actor_username);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_ministry_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_manager_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_project_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Service role full access for backend API operations
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'service_role_users_all') THEN
        CREATE POLICY "service_role_users_all" ON users FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_ministry_assignments' AND policyname = 'service_role_uma_all') THEN
        CREATE POLICY "service_role_uma_all" ON user_ministry_assignments FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'project_manager_assignments' AND policyname = 'service_role_pma_all') THEN
        CREATE POLICY "service_role_pma_all" ON project_manager_assignments FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'daily_project_updates' AND policyname = 'service_role_dpu_all') THEN
        CREATE POLICY "service_role_dpu_all" ON daily_project_updates FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'audit_logs' AND policyname = 'service_role_audit_all') THEN
        CREATE POLICY "service_role_audit_all" ON audit_logs FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
END
$$;
